### ISSUE TITLE
names or rownames

### ISSUE THREAD

**Issue by lgatto** [magnuspalmblad/NGP#1]
I am following the code in `simulations.R` and on line [26](https://github.com/magnuspalmblad/NGP/blob/0bb6aaee112f340d8814a706fecd719fef0bf5a4/simulations.R#L26), I believe

```r
names(proteins) <- nextprot[1:N_PROTEINS]
```
should be
```r
rownames(proteins) <- nextprot[1:N_PROTEINS]
```
as `proteins` is a `data.frame` of proteins with two columns, namely `"NEXTPROT"` and `"SEQUENCE"`. And even so, the nextprot identifier is already available, so it could be dropped entirely.

I had to slightly change the code because of Uniprot being temperamental with the number of queries, so I might have mixed something up - if so, aplogies.

**Comment by magnuspalmblad** [comment]
Thanks! So the uniprot.ws calls work for you? I have had issues with them recently, though they worked fine when I first ran the code. If you have more improvements/corrections, I can merge them and add you as a contributor to the project.

**Comment by lgatto** [comment]
At the moment, I hit 
```r
> up <- UniProt.ws(taxId = 9606)

Error in readLines(idUrl) : cannot read from connection
In addition: Warning message:
In readLines(idUrl) :
  URL 'https://www.uniprot.org/uniprot/?query=organism:9606&format=tab&columns=id': Timeout of 60 seconds was reached
```
but opening that url in a browser worked, so I created the `UniProt.ws` object by hand.

**Comment by magnuspalmblad** [comment]
I get timeout errors in the subsequent step:

```
> up <- UniProt.ws(taxId = 9606)
> nextprot <- keys(up, keytype = "NEXTPROT")
Getting mapping data for Q96R72 ... and NEXTPROT_ID
error while trying to retrieve data in chunk 1:
    no results after 5 attempts; please try again later
continuing to try
error while trying to retrieve data in chunk 2:
    no results after 5 attempts; please try again later
continuing to try
error while trying to retrieve data in chunk 3:
    no results after 5 attempts; please try again later
continuing to try
```

As it used to work, I can only assume something changed on the server side. If this is not resolved, I will change the script to load the sequence data via FTP. Less elegant, but at least it should work. Closing this, as the original issue has been addressed.

**Comment by lgatto** [comment]
I also got these errors - to get around them, I split the query in smaller chunks and then `rbind()`ed the resulting data.frame to the previous one. That solved it.
