### ISSUE TITLE
Two minor suggestions

### ISSUE THREAD

**Issue by lgatto** [magnuspalmblad/NGP#2]
1. Line [62](https://github.com/magnuspalmblad/NGP/blob/main/simulations.R#L62) of the simulations could simply be `if (!IDEAL)`.
2. The `plots.R` files assumes that the simulation results are in the working directory. The names of the files could this include the directory name `./simulation_results/` to be able to directly execute the plotting code.

**Comment by lgatto** [comment]
Happy to send a PR if you wish.

**Comment by magnuspalmblad** [comment]
I made the suggested changes, as they were really minor, but if you have other corrections/improvements, I'm happy to pull these into main.
